### PR TITLE
Added /f truce

### PR DESCRIPTION
**Pull request by ctooley17**
Completes issue #12

### CODE REVIEW

**Comment by Spazzinq** [comment]
@ctooley17 Can we get a download? Also, is it added to the "/f who" ? Thanks for updating it :)

**Comment by ctooley17** [comment]
Ah, forgot about /f who. Will finish that and send you a jar,

**Comment by Spazzinq** [comment]
@ctooley17 And I'm guessing it's in the lang file too right? :) Can you maybe take a look at #23 and see what's up? The scoreboard is pretty essential for my server.

**Comment by ctooley17** [comment]
Here is a dl till @MarkehMe goes over my code and accepts the pr. https://www.dropbox.com/s/ukxq75kuubtcbn7/LegacyFactions-1.3.0-all.jar?dl=0

**Comment by MarkehMe** [comment]
@Spazzinq if you can report back with how you go through testing it out too, it will really help :)

**Comment by Spazzinq** [comment]
@MarkehMe @ctooley17 I don't see any issues not current with the latest version 1.3.0! P.S. When entering the command "/f chat" multiple times and cycling through the options truces don't appear, only allies, global, and faction appear. Also, if you could fix #23 and the scoreboard, that would be AWESOME! Thanks for being great developers 👍 

--
~Spazzinq

**Comment by Spazzinq** [comment]
You guys should also make a discord. It would be easier for communication. Also, is there an option in one of the configs to edit the nametag formatting? I wish to edit it.

**Comment by ctooley17** [comment]
@Spazzinq added truce to /f chat cycle

**Comment by Spazzinq** [comment]
Found an error while messing around on my beta testing server. Also, TacoSpigot and PaperSpigot are so similar to Spigot with my experience, all errors happen that occur on TacoSpigot and PaperSpigot also occur on spigot, if that's worth noting. 

P.S. here's the error
[https://gist.github.com/Spazzinq/d1c6402954e866a14ee368306b35329b](https://gist.github.com/Spazzinq/d1c6402954e866a14ee368306b35329b)

**Comment by Spazzinq** [comment]
You may also want to add territoryTruceDenyCommands [https://gyazo.com/64421674233fa0e5dd747a76c0b7725a](https://gyazo.com/64421674233fa0e5dd747a76c0b7725a)

**Comment by ctooley17** [comment]
@Spazzinq 
added that as well, also it is odd that you're getting that error, as that method (p.getInventory().getItemInMainHand()) does exist...

**Comment by Spazzinq** [comment]
Just an idea, maybe you could add some sort of thing where instead of having a chat option for when you move territories, it was with titles instead (/title) (Similar to the junk-filled factions 2)

**Comment by ctooley17** [comment]
@Spazzinq I could add that if @MarkehMe supports the idea.

**Pull request merged**
