### PR TITLE
Fire disband event on last player leaving

### PR DESCRIPTION
**Pull request by novucs**

### CODE REVIEW

**Comment by MarkehMe** [comment]
Thank you so much for your pull request! I appreciate it a lot.

However, I'm not sure this is the best place to call the event.

Perhaps it should be called in the `FPlayer#leave` method [here](https://github.com/redstone/LegacyFactions/blob/master/src/main/java/net/redstoneore/legacyfactions/entity/persist/memory/MemoryFPlayer.java#L721-L731
)? This way the event gets called all the time. Say, another plugin calling it.

**Comment by novucs** [comment]
You're right, that would be a better method of doing this. Though I'm just about heading to sleep now, I'll correct this when I get time tomorrow unless you feel like changing it yourself.

**Comment by novucs** [comment]
Resolved in the latest commit.

**Comment by MarkehMe** [comment]
Looks great, thank you so much for contributing! It's greatly appreciated! ❤️

**Pull request merged**
