### PR TITLE
chatTag

### PR DESCRIPTION
**Pull request by Neeonn**
Chat tag doesn't work with DeluxeChat.

Versions: `LegacyFactions - 1.4.7, DeluxeChat - 1.12.7, PlaceholderAPI - 2.9.1`
F Debug: https://file.properties/paste/bebikupeye.md

Screenshots: 
image 
image
image
image
image

### CODE REVIEW

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by Neeonn** [comment]
I can use placeholders like %factions_faction_name% and etc and they work but I want to use %factions_chat_tag% as I used the factionless custom tag (It says Wilderness for factionless people when using placeholder for fac name).

**Comment by Neeonn** [comment]
Bump! Please answer I need this.

**Comment by Neeonn** [comment]
Bump!

**Comment by Neeonn** [comment]
Bump?

**Comment by Neeonn** [comment]
Fixed the issue.

**Pull request closed without merging**
