### PR TITLE
2 errors 1 persistent and 1 error with the chat (with EssentialsX)

### PR DESCRIPTION
**Pull request by Antyss77**
Server version: 1.12.2
Plugin version: 1.4.7 LegacyFaction
Plugin link: https://www.spigotmc.org/resources/legacyfactions.40122/
Pastebin/hastebin links where the error occurs: https://hastebin.com/cajivofupu.md
Details: I have this persistent error on the LegacyFaction plugin, after several reboot the error is still present (no support for this plugin)

2) : 

Server version: 1.12.2 
Plugin Version: 1.4.7 LegacyFaction
Plugin link: https://www.spigotmc.org/resources/legacyfactions.40122/
Details: I try to configure the chat format (Rank in faction, name of the faction, nickname, message) however when I do so in the conf.json file like this: https://prnt.sc/u51ap1
Here is the result displayed in game: https://prnt.sc/u51av6 Of course, I tried to put the items: {factions_player_role_prefix} & {factions_faction_name} in the chat part of Essentials (in the config.yml file) (EssentialsX: 2.18) however the result is even worse someone would have an idea how to configure this plugin? The tutorials, the doc doesn't say more about it

### CODE REVIEW

**Comment by Antyss77** [comment]
By doing this: https://prnt.sc/u53a6u I managed to get a more visually attractive result however I would like each grade to write in a different color and I can't define this, is it possible to define the prefix (roles, faction name...) in essentials directly? What would make it possible for me to have different colors depending on the grade in the chat? https://prnt.sc/u53axg

**Comment by Antyss77** [comment]
And now: https://prnt.sc/u53e6c But I still can't make it a different color in the chat for each grade

**Comment by Antyss77** [comment]
When I put: §8 [§6<classification>§8] §8 [§7{factions_player_role_prefix} §7{factions_faction_name}§8]
In the essentials configuration file here is the result :
https://prnt.sc/u53k4i

What can I please do?

**Comment by markhughes** [comment]
Do you use a supported plugin?

https://github.com/redstone/LegacyFactions/wiki/Placeholders

**Comment by Antyss77** [comment]
Oh, but it's mandatory to have this? I thought I could use essentials chat :x

**Comment by Antyss77** [comment]
Hello,
Do you think you can add compatibility with EssentialsX or Luckperms? I know the plugin is open source and that's fine, but I don't have the skills to do that yet

**Pull request closed without merging**
